// TRANSACTION TYPE

const TRANSACTION_TYPE_INCOME = 1;
const TRANSACTION_TYPE_EXPENSE = 0;

// TRANSACTION TYPE
const CATEGORY_TYPE_INCOME = 1;
const CATEGORY_TYPE_EXPENSE = 2;
const CATEGORY_TYPE_UNNECSSARY_EXPENSE = 3;